=== RodrigoProjects/PRI2020/TPC2/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT project (key_name, title, subtitle?, begin_date, end_date, supervisor, work_team, abstract, deliverables)>

<!ELEMENT key_name (#PCDATA)>

<!ELEMENT title (#PCDATA)>

<!ELEMENT subtitle (#PCDATA)>

<!ELEMENT begin_date (#PCDATA)>

<!ELEMENT end_date (#PCDATA)>

<!ELEMENT supervisor (#PCDATA)>
<!ATTLIST supervisor 
    url CDATA #IMPLIED>

<!ELEMENT work_team (elemento)+ >
<!ELEMENT elemento (nome, numero, email)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT abstract (paragraph)+ >
<!ELEMENT paragraph (#PCDATA | bold | italic | underline | link)* >
<!ELEMENT bold (#PCDATA)>
<!ELEMENT italic (#PCDATA)>
<!ELEMENT underline (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link 
    url CDATA #REQUIRED>

<!ELEMENT deliverables (file | folder)+ >
<!ELEMENT file (#PCDATA)>
<!ATTLIST file
    url CDATA #REQUIRED>
<!ELEMENT folder (file | folder)+ >
<!ATTLIST folder
    name CDATA #REQUIRED>

=== RodrigoProjects/PRI2020/TPC2/TPC2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project SYSTEM "file:/home/rodrigo/Desktop/4ano/PRI/PRI2020/TPC2/PR.dtd">
<project>
    <key_name>PRI2020_TPCS_2</key_name>
    <title>TPC2 - DTD e XML</title>
    <begin_date>Outobro 2020</begin_date>
    <end_date>Outobro 2020</end_date>
    <supervisor url="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
    <work_team>
        <element>
            <nome>Rodrigo da Silva Pimentel</nome>
            <numero>a83765</numero>
            <email>a83765@alunos.uminho.pt</email>
        </element>
    </work_team>
    <abstract>
        <paragraph> TPC com objetivo de praticar o uso de <bold>DTD</bold>s. <italic>Schema</italic> responsável por definir a estrutura de um <italic>project record   </italic> e um ficheiro exemplo que respeite o <italic>schema</italic>.</paragraph>
    </abstract>
    <deliverables>
        <file path="./TPC2.xml">TPC2 XML Example</file>
        <file path="./PR.dtd">Project Record DTD</file>
    </deliverables>
</project>

=== RodrigoProjects/PRI2020/TPC3/TPC3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project SYSTEM "file:/home/rodrigo/Desktop/4ano/PRI/PRI2020/TPC2/PR.dtd">
<project>
    <key_name>PRI2020_TPCS_3</key_name>
    <title>TPC3 - DTD e XSL</title>
    <begin_date>Outobro 2020</begin_date>
    <end_date>Novembro 2020</end_date>
    <supervisor url="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
    <work_team>
        <element>
            <nome>Rodrigo da Silva Pimentel</nome>
            <numero>a83765</numero>
            <email>a83765@alunos.uminho.pt</email>
        </element>
    </work_team>
    <abstract>
        <paragraph> TPC com objetivo de praticar o uso de transformações em <bold>XSL</bold>. Criar um <italic>website</italic> a partir do <link url="ARQSITS.xml">ARQSITS.xml</link></paragraph>
    </abstract>
    <deliverables>
        <file path="./TPC3.xml">TPC3 Project Record</file>
        <file path="./ARQSITS.dtd">ARQSITS DTD</file>
        <file path="./ARQ2HTML.xsl">XSL for ARQSITS</file>
        <file path="./ARQSITS.xml">ARQSITS Data</file>
        <folder name="site">
            <file path="./ARQSITS.html">ARQSITS HTML</file>
            <file path="./script.js">Script of ARQSITS site</file>
        </folder>
    </deliverables>
</project>
